baseURL: "https://dandielo.github.io/"
languageCode: "en-us"
title: "Digital Cake"
theme: "hugo-PaperMod"
paginate: 5

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpored: false

minify:
  disableXML: true
  minifyOutput: true

menu:
  main:
    - name: IceShard - Engine
      url: /iceshard/
      weight: 1
    - name: Archives
      url: /archives/
      weight: 5
    - name: Tags
      url: /tags/
      weight: 10

taxonomies:
  category: categories
  tag: tags
  series: series

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Bits, Bytes and Cake
  description: 'A blog about anything, however mostly centered about programming and cooking.'
  author: Dandielo

  # images: "<link or path of image for opengraph, twitter-cards>"

  ShowReadingTime: true
  ShowShareButtons: false
  comments: true
  defaultTheme: auto
  disableThemeToggle : false
  disableSpecial1stPost : false

  # # profile-mode
  # profileMode:
  #   enabled: false # needs to be explicitly set
  #   title: ExampleSite
  #   # imageUrl: '<img location>'
  #   # imageTitle: my image
  #   buttons:
  #   - name: Posts
  #     url: posts
  #   - name: Tags
  #     url: tags

  # home-info mode
  homeInfoParams:
    Title: A different way of sharing
    Content: >
      And here I am writing a blog.
      Something I was never thinking of.


      Just to introduce myself, a self-taught programmer, always looking for the next thing to learn.
      Now I am at a place where sharing my thoughts might help someone else.


      I hope you are going to enjoy the topics and follow my journey.


      -- Dandielo

  socialIcons:
    - name: github
      url: 'https://github.com/Dandielo/'


  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
